//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>Дом</remarks>
public class House
{
	/// <summary>
	/// Количество квартир в дому
	/// </summary>
	private int n_apartments
	{
		get;
		set;
	}

	private Apartment * apartments
	{
		get;
		set;
	}

	/// <summary>
	/// Сколько жильцов добавлено через метод AddPerson
	/// </summary>
	private int size
	{
		get;
		set;
	}

	private char * address
	{
		get;
		set;
	}

	public virtual IEnumerable<Apartment> Apartment
	{
		get;
		set;
	}

	public virtual void AddApartment(Apartment ap)
	{
		throw new System.NotImplementedException();
	}

	public House()
	{
	}

	public House(int n)
	{
	}

	public ~House()
	{
	}

	/// <summary>
	/// Конструктор копирования
	/// </summary>
	public House(const House& orig)
	{
	}

	public virtual void show()
	{
		throw new System.NotImplementedException();
	}

}

