//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <remarks>Человек</remarks>
public class Person
{
	/// <summary>
	/// Фамилия, имя, отчество
	/// </summary>
	private char * fio
	{
		get;
		set;
	}

	/// <summary>
	/// Возраст
	/// </summary>
	private int age
	{
		get;
		set;
	}

	public Person()
	{
	}

	public Person(char * fio, int age)
	{
	}

	public Person(const Person & orig)
	{
	}

	public ~Person()
	{
	}

	public virtual void show()
	{
		throw new System.NotImplementedException();
	}

	public virtual Person operator=(const Person & orig)
	{
		throw new System.NotImplementedException();
	}

}

